### ISSUE TITLE
Missing mapzen dependencies

### ISSUE THREAD

**Issue by stantond** [whosonfirst/py-mapzen-whosonfirst-spatial#6]
```
Installed c:\program files\python35\lib\site-packages\mapzen.whosonfirst.spatial-0.12-py3.5.egg
Processing dependencies for mapzen.whosonfirst.spatial==0.12
Searching for mapzen.whosonfirst.uri>=0.1
Reading https://pypi.python.org/simple/mapzen.whosonfirst.uri/
Couldn't find index page for 'mapzen.whosonfirst.uri' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for mapzen.whosonfirst.uri>=0.1
error: Could not find suitable distribution for Requirement.parse('mapzen.whosonfirst.uri>=0.1')
```

This happened with:
- mapzen.whosonfirst.uri
- mapzen.whosonfirst.meta
- \- mapzen.whosonfirst.placetypes.utils (required by .meta)

I'm on Windows 10 using Python 3.5.

**Comment by thisisaaronland** [comment]
Ah, yes – sorry. That's a missing dependency in the `setup.py` file. The really short version is that this package should install all the dependencies (and then some):

https://github.com/whosonfirst/py-mapzen-whosonfirst

The longer version is that the dependency stuff is still a bit of a mess because we're still figuring it out all out. I will update the immediate problem in this package and add some copy about the wrapper package to all the other packages.

**Comment by thisisaaronland** [comment]
Closing this (for now) per: https://github.com/whosonfirst/py-mapzen-whosonfirst-spatial/blob/master/requirements.txt
